# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-
# stub: railsless-deploy 1.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "railsless-deploy"
  s.version = "1.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lee Hambley"]
  s.date = "2013-12-13"
  s.description = "Replacement for the rails deploy strategy which ships with Capistrano, allows you to deploy any platform with ease; some people have had huge success with this deploying rails projects where they needed to customise their deploy strategy beyond the code which ships with the Capistrano gem."
  s.email = "lee.hambley@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.markdown",
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
    "CHANGELOG.markdown",
    "LICENSE.markdown",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/railsless-deploy.rb",
    "railsless-deploy.gemspec"
  ]
  s.homepage = "http://github.com/leehambley/railsless-deploy/"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.10"
  s.summary = "Replacement for the default Capistrano tasks, designed to make life easier for PHP/Perl/Python developers"
end
